//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM4UDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipCard
    {
        public System.Guid Id { get; set; }
        public int CardNumber { get; set; }
        public System.DateTime Expired { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public System.Guid UpdatedByUserId { get; set; }
        public bool IsActive { get; set; }
        public System.Guid MembershipTypeId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Member Member { get; set; }
        public virtual MembershipType MembershipType { get; set; }
    }
}
